Build 1.1.6

diff --git a/roles/addvm/tasks/set.vm.yml b/roles/addvm/tasks/set.vm.yml
--- a/roles/addvm/tasks/set.vm.yml
+++ b/roles/addvm/tasks/set.vm.yml
@@ -1,9 +1,46 @@
 ---
 
-- name: Set network
-  shell: 'qm set {{ args_proxmox_vmid }} --net0 model=virtio,macaddr={{ args_vm_mac }},bridge=vmbr0,firewall=1,tag={{ args_vm_vlan }} >/dev/null 2>&1 ; echo $?'
+- name: Set network1
+  shell: |
+    if [ "{{ args_vm_mac | default('none') }}" != 'none' ]; then
+      net=model=virtio,macaddr={{ args_vm_mac }},bridge=vmbr0,firewall=1
+      if [ "{{ args_vm_vlan }}" -gt "0" ]; then
+        net=$net,tag={{ args_vm_vlan }}
+      fi
+      echo $net
+      qm set {{ args_proxmox_vmid }} --net0 $net
+      if [ "$?" -eq "0" ]; then
+        echo "CHANGED"
+      else
+        echo "FAILED"
+      fi
+    else
+      echo "NONE"
+    fi
   register: result
-  changed_when: '"0" in result.stdout'
+  changed_when: '"CHANGED" in result.stdout'
+  failed_when: '"FAILED" in result.stdout'
+
+- name: Set network2
+  shell: |
+    if [ "{{ args_vm_mac2 | default('none') }}" != 'none' ]; then
+      net=model=virtio,macaddr={{ args_vm_mac2 }},bridge=vmbr0,firewall=1
+      if [ "{{ args_vm_vlan2 | default('0') }}" -gt "0" ]; then
+        net=$net,tag={{ args_vm_vlan2 }}
+      fi
+      echo $net
+      qm set {{ args_proxmox_vmid }} --net1 $net
+      if [ "$?" -eq "0" ]; then
+        echo "CHANGED"
+      else
+        echo "FAILED"
+      fi
+    else
+      echo "NONE"
+    fi
+  register: result
+  changed_when: '"CHANGED" in result.stdout'
+  failed_when: '"FAILED" in result.stdout'
 
 - name: Set memory
   shell: 'qm set {{ args_proxmox_vmid }} --memory {{ args_vm_memory }} >/dev/null 2>&1 ; echo $?'
