Build 1.3.42

diff --git a/roles/rebootvm/tasks/main.yml b/roles/rebootvm/tasks/main.yml
--- a/roles/rebootvm/tasks/main.yml
+++ b/roles/rebootvm/tasks/main.yml
@@ -5,7 +5,7 @@
 
 - name: shutdown [{{ prop_proxmox_vmid }}]
   shell: |
-    qm reboot {{ prop_proxmox_vmid }}
+    qm shutdown {{ prop_proxmox_vmid }} --skiplock --forceStop
     if [ "$?" -ne "0" ]; then
       echo "FAILED"
       exit 1
@@ -30,4 +30,29 @@
 - ansible.builtin.include_role:
     name: alex.proxmox.startvm
 
+
+
+# - name: reboot [{{ prop_proxmox_vmid }}]
+#   shell: |
+#     qm reboot {{ prop_proxmox_vmid }}
+#     if [ "$?" -ne "0" ]; then
+#       echo "FAILED"
+#       exit 1
+#     fi
+#     qm wait {{ prop_proxmox_vmid }}
+#     if [ "$?" -eq "0" ]; then
+#       echo "CHANGED"
+#     else
+#       echo "FAILED"
+#     fi
+#   args:
+#     executable: /bin/bash
+#   when: '"RUNNING" in result_status.stdout'
+#   register: result
+#   changed_when: '"CHANGED" in result.stdout'
+#   failed_when: '"FAILED" in result.stdout'
+#   vars:
+#     ansible_connection: ssh
+#     ansible_host: "{{ prop_proxmox_host }}"
+#   become: true
 
