Build 1.1.9

diff --git a/roles/removevm/tasks/main.yml b/roles/removevm/tasks/main.yml
--- a/roles/removevm/tasks/main.yml
+++ b/roles/removevm/tasks/main.yml
@@ -1,3 +1,13 @@
 ---
 
-- include_tasks: remove.vm.yml
+- name: remove vm
+  shell: |
+    qm destroy {{ args_vmid }} --skiplock --purge
+    if [ "$?" -eq "0" ]; then
+      echo "CHANGED"
+    else
+      echo "FAILED"
+    fi
+  register: result
+  changed_when: '"CHANGED" in result.stdout'
+  failed_when: '"FAILED" in result.stdout'
diff --git a/roles/shutdownvm/tasks/main.yml b/roles/shutdownvm/tasks/main.yml
--- a/roles/shutdownvm/tasks/main.yml
+++ b/roles/shutdownvm/tasks/main.yml
@@ -1,8 +1,13 @@
 ---
 
-- name: start vm
+- name: shutdown vm
   shell: |
-    qm start {{ args_vmid }}
+    qm shutdown {{ args_vmid }} --skiplock --forceStop
+    if [ "$?" -ne "0" ]; then
+      echo "FAILED"
+      exit 1
+    fi
+    qm wait {{ args_vmid }}
     if [ "$?" -eq "0" ]; then
       echo "CHANGED"
     else
diff --git a/roles/stopvm/tasks/main.yml b/roles/stopvm/tasks/main.yml
--- a/roles/stopvm/tasks/main.yml
+++ b/roles/stopvm/tasks/main.yml
@@ -1,3 +1,13 @@
 ---
 
-- include_tasks: stop.vm.yml
+- name: stop vm
+  shell: |
+    qm stop {{ args_vmid }} --skiplock
+    if [ "$?" -eq "0" ]; then
+      echo "CHANGED"
+    else
+      echo "FAILED"
+    fi
+  register: result
+  changed_when: '"CHANGED" in result.stdout'
+  failed_when: '"FAILED" in result.stdout'
